### PR TITLE
Add contributor guide and code of conduct

### PR DESCRIPTION
**Pull request by slobentanzer**

### CODE REVIEW

**Comment by slobentanzer** [comment]
Appears the auto check works :)

**Comment by ktpolanski** [comment]
I don't think there's a reason to bump version as nothing has changed in the functionality

**Comment by slobentanzer** [comment]
The bump was a test of the bump2version package auto-update. We can revert the version manually, or we can make the update due to the additions that Nick made recently (`0.1.1`), since they were in parallel with the PR for `0.2.0`. I think those changes are still present after the PR merge, right?

**Comment by slobentanzer** [comment]
Yes, git tags [can be deleted](https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/) (also possible on the GitHub UI on the Tags page). I have done so on my fork.

**Comment by slobentanzer** [comment]
We can remove it; I just find it helps with consistency. I often forget to create a tag for a patch, for instance. If you introduce multiple places of your version later (as for example happened with BioCypher), you can easily add that to the bumpversion workflow and replace everywhere at once.

Additionally, even if the PR creator does not (should not) bump, it still can be used by the responsible person on your side to save a bit of labour. This can be indicated in the contributor guide (please do not increment the version, we will do that...) instead of the current guideline.

If you still want to remove it, let me know.

**Comment by ktpolanski** [comment]
You've made a reasonable argument for it to stay. I'd imagine if there will be more places the version goes, you'll be the one responsible :P

In that case, could you amend the various guides as appropriate to make it clear that version bumping is not typically expected? I associate doing a version bump with the last seconds before something goes up on pip.

**Comment by ktpolanski** [comment]
Seeing how there's chatter of docs themes (RTD theme would be nice but it's up to you really), altering the various codes of conduct to stress version bumping is not expected of the typical PR is all there's left. I'll merge when done.

**Comment by slobentanzer** [comment]
I updated the guide. I also like RTD, let's go with that.

**Comment by slobentanzer** [comment]
Yes, you need to call `bumpversion` with `patch`, `minor`, or `major`, and then it does a number of things depending on the config. You can dry-run using the `-n` flag with `--verbose`, then it will show you what it would do without touching your files.

I activated commit and tag features, mainly because these are just busywork and in the case of tags also very forgettable, but if you don't want that, you can also set them to false in the .bumpversion.cfg. 

Here are the docs: https://github.com/c4urself/bump2version

**Comment by ktpolanski** [comment]
Onward to the final hurdle, docs!

**Comment by ktpolanski** [comment]
Also I just tried `bumpversion patch` locally and it did indeed make a commit and a tag and everything on my behalf. This is kind of neat. Thanks for bringing it to my attention.

**Pull request merged**
